/** Bot names. There are more names than the 29 bots a full room can hold. */
export const BOT_NAMES = [
  'Chomper',
  'Spike',
  'Talon',
  'Fang',
  'Bruno',
  'Pebbles',
  'Gnasher',
  'Moss',
  'Echo',
  'Ziggy',
  'Tango',
  'Biscuit',
  'Nova',
  'Ripley',
  'Diesel',
  'Juno',
  'Mango',
  'Pixel',
  'Thorn',
  'Coco',
  'Rocco',
  'Dash',
  'Kiwi',
  'Olive',
  'Quill',
  'Rexy',
  'Sable',
  'Bramble',
  'Clover',
  'Jasper',
] as const;

/** Big plant-eaters whose carcasses turn up as world events, worth fighting over. */
export const CARCASS_SPECIES = [
  'Brachiosaurus',
  'Triceratops',
  'Stegosaurus',
  'Ankylosaurus',
  'Parasaurolophus',
  'Diplodocus',
] as const;
